name: prog_calc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SometypeMono
      fonts:
        - asset: assets/fonts/SometypeMono-Regular.ttf
        - asset: assets/fonts/SometypeMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/SometypeMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SometypeMono-Italic.ttf
          style: italic
        - asset: assets/fonts/SometypeMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SometypeMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/SometypeMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SometypeMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
